// <auto-generated />
namespace Hdnug.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-beta1-30206")]
    public sealed partial class SponsorImageCascadeDelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SponsorImageCascadeDelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201512231551433_SponsorImageCascadeDelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
